[RHM-1969] Gloat should support rollback of migrations.
webedx-spark/gloat pull request #1
Opened 2022-03-10 06:33 UTC by ndyakov

For rhyme to be able to rollback to a prior version our migrations library was forked and additional features were implemented.
There are two possible ways for reverting migrations between versions:
1. If both version are on the same base `migrate to <version>` can be used. In that case migrations applied after `<version>` will be reverted.
- to get the latest migration that is part of a given version, there is `migrate latest` command.
- for correct ordering of migrations `applied_at` field is being added to the database.
3. If the two versions are not part of the same node and their migrations may be applied out of order, the `migrate keep <list,of,versions,to,keep>` can be used. In that case, all migrations listed (in the comma separated list) will be kept, the rest that are applied will be reverted.
- to generate the list of migrations that are part of a given version, there is `migrate present` command.
- for correct ordering of migrations `applied_at` field is being added to the database.

To deploy this feature, the changes of the `schema_migrations` table should be executed manually:
```
ALTER TABLE schema_migrations 
ADD COLUMN applied_at timestamp without time zone default (now() at time zone 'utc');

CREATE INDEX IF NOT EXISTS schema_migrations_applied_at 
ON schema_migrations (applied_at);

```
https://coursera.atlassian.net/browse/RHM-1969

TODO:
[] tests
[] update help
[] write deployment steps

2022-03-15 07:59 UTC, borisbsv requested changes
We use https://pkg.go.dev/github.com/stretchr/testify/assert for assertions, let's drop `gsamokovarov/assert`

2022-03-15 07:59 UTC, borisbsv commented on cmd/gloat/main.go
> +func toCmd(args arguments) error {
By convention the name `toCmd` looks like it should convert the arguments to a `Cmd`, can we improve the naming a bit?

2022-03-15 07:59 UTC, borisbsv commented on migration.go
> +		AppliedAt: time.Now(),
Let's just in case, use `time.Now().UTC()` for consistency across platforms?

2022-03-15 07:59 UTC, borisbsv commented on migration.go
>  	now = time.Now().UTC()
Let's delete this variable it's only used in a single function and is initialized every time you load the package.

2022-03-15 07:59 UTC, borisbsv commented on migration.go
> +	}
Do we sort here? If not, we implicitly rely on the db's internals and that's not guaranteed to be stable - you might append migrations that were applied before the one you're looking for

2022-03-15 07:59 UTC, borisbsv commented on migration.go
> +func (m Migrations) Intersect(migrations Migrations) (intersect Migrations) {
the variables `m`, `migrations` and `intersect` aren't super clear here, can we rename `migrations` to `others` or `intersectWith` and `intersect` with `result`?
Side note, using named returns isn't a good practice unless necessary.

2022-03-16 15:32 UTC, Hepri approved these changes
Looks good

2022-03-18 00:43 UTC, ndyakov commented
@borisbsv can you check this PR again.

2022-03-18 15:20 UTC, borisbsv approved these changes
Merge on :)

2022-03-30 15:50 UTC, merged